import { describe, expect, it, vi, afterEach } from "vitest";
import { readFileSync } from "node:fs";
import {
  approvedFixture,
  hydrate,
  validateFixture,
  validateProject,
  upperBound,
  canonical,
} from "./data";
import type { Fixture, Manifest, Project } from "./data";
import { direction, ema, opacity, radius, observations } from "./signal";
import {
  calibrate,
  correctCounter,
  distanceInterval,
  locate,
} from "./localization";
import { durability } from "./storage";
import { useUI } from "./store";
const manifest: Manifest = JSON.parse(
  readFileSync("public/fixtures/manifest.json", "utf8"),
);
const fixture = (id = "triangle"): Fixture =>
  JSON.parse(readFileSync(`public/fixtures/${id}.json`, "utf8"));
const project = (f: Fixture): Project => ({
  kind: "synthetic-ble-project",
  schema_version: 1,
  synthetic: true,
  fixture: f,
  view: {
    time_ms: 12000,
    selected: 0,
    tau: 0.7,
    positions: f.receivers.map(({ id, x_m, y_m }) => ({ id, x_m, y_m })),
    clock_corrected: true,
  },
});
describe("synthetic provenance and schema", () => {
  for (const entry of manifest.fixtures)
    it(`validates every generated byte: ${entry.id}`, async () => {
      const f = fixture(entry.id);
      expect(await approvedFixture(f, manifest)).toBe(f);
      expect(f.events.t.length).toBe(entry.event_count);
      const s = hydrate(f);
      expect(s.indices.reduce((a, x) => a + x.length, 0)).toBe(s.t.length);
      expect(s.t).toBeInstanceOf(Uint32Array);
    });
  it("rejects altered observations and unknown identifying fields", async () => {
    const f = fixture();
    f.events.rssi[0]++;
    await expect(approvedFixture(f, manifest)).rejects.toThrow("generator");
    expect(() =>
      validateFixture({ ...fixture(), extra: "unsupported" }),
    ).toThrow();
  });
  it("rejects reversed time and unequal arrays while preserving ties", () => {
    const f = fixture();
    expect(f.events.t.some((t, i, a) => i > 0 && t === a[i - 1])).toBe(true);
    f.events.t[1] = 100;
    expect(() => validateFixture(f)).toThrow("nondecreasing");
    const g = fixture();
    g.events.rssi.pop();
    expect(() => validateFixture(g)).toThrow("different lengths");
    expect(upperBound([1, 1, 1, 3], 1)).toBe(3);
    expect(upperBound([1, 1, 1, 3], 0)).toBe(0);
  });
  it("round trips backups and rejects mismatched receiver layouts", async () => {
    const p = project(fixture());
    expect(await validateProject(JSON.parse(canonical(p)), manifest)).toEqual(
      p,
    );
    p.view.positions[1].id = p.view.positions[0].id;
    await expect(validateProject(p, manifest)).rejects.toThrow("layout");
  });
});
describe("signal semantics", () => {
  it("maps stronger signals inward and flags outliers", () => {
    const values = [-120, -110, -80, -40, -10].map((x) => radius(x).r);
    expect(values).toEqual([...values].sort((a, b) => b - a));
    expect(radius(-121).clamped).toBe(true);
    expect(radius(-9).clamped).toBe(true);
  });
  it("uses time-aware smoothing and exact inactivity boundaries", () => {
    expect(() => ema(-80, -50, -1, 1)).toThrow();
    expect(ema(-80, -50, 0, 1)).toBe(-80);
    expect(Math.abs(ema(-80, -50, 3, 1) + 50)).toBeLessThan(1.5);
    expect(opacity(2000)).toBe(1);
    expect(opacity(7999)).toBeGreaterThan(0);
    expect(opacity(8000)).toBe(0);
  });
  it("keeps assigned directions and selected state stable through seeks", () => {
    const initial = direction(3),
      s = hydrate(fixture());
    for (let time = 0; time <= 48000; time += 1000) {
      observations(s, time, 0, 0.7);
      expect(direction(3)).toEqual(initial);
    }
    useUI.setState({ selected: 3, query: "Beacon 004" });
    useUI.getState().seekTo(30000);
    expect(useUI.getState()).toMatchObject({
      selected: 3,
      time: 30000,
      query: "Beacon 004",
    });
  });
});
describe("conditional estimation", () => {
  it("fits a known calibration and inverts its prediction band", () => {
    const m = calibrate(fixture().receivers[0].calibration);
    expect(m.reference).toBeCloseTo(-55, 1);
    expect(m.exponent).toBeCloseTo(2, 1);
    const band = distanceInterval(-75, m);
    expect(band.low).toBeLessThan(10);
    expect(band.high).toBeGreaterThan(10);
    expect(band.point).toBeCloseTo(10, 0);
  });
  it("rejects unresolved slopes without silently returning a point", () => {
    const m = calibrate(fixture("weak-fit").receivers[0].calibration);
    expect(distanceInterval(-75, m).point).toBeNull();
    expect(() => calibrate([{ distance_m: 1, rssi: -60 }])).toThrow();
  });
  it("corrects offset and drift without using wall-clock time", () => {
    const f = fixture("clock-drift");
    for (let i = 0; i < f.events.t.length; i += 100) {
      const r = f.receivers[f.events.receiver[i]];
      expect(
        Math.abs(correctCounter(f.events.counter_ms[i], r) - f.events.t[i]),
      ).toBeLessThan(0.51);
    }
  });
  it("provides a useful three-receiver estimate with metric sensitivity", () => {
    const f = fixture(),
      fix = locate(hydrate(f), 0, 12000, f.receivers, true);
    expect(fix.point).not.toBeNull();
    expect(
      Math.hypot(
        fix.point!.x - f.beacons[0].x_m,
        fix.point!.y - f.beacons[0].y_m,
      ),
    ).toBeLessThan(6);
    expect(fix.sensitivity).toBeGreaterThan(0);
  });
  for (const id of ["collinear", "sparse", "weak-fit"])
    it(`returns no fix for ${id}`, () => {
      const f = fixture(id);
      expect(locate(hydrate(f), 0, 12000, f.receivers, true).point).toBeNull();
    });
  it("blocks uncorrected clocks and expired sparse evidence", () => {
    const f = fixture("clock-drift");
    expect(locate(hydrate(f), 0, 12000, f.receivers, false).point).toBeNull();
    expect(locate(hydrate(f), 4, 30000, f.receivers, true).point).toBeNull();
  });
});
describe("storage disclosure", () => {
  afterEach(() => vi.unstubAllGlobals());
  it("distinguishes unrequested persistence from an actual refusal", async () => {
    const persist = vi.fn(async () => false);
    vi.stubGlobal("navigator", {
      storage: { persisted: async () => false, persist },
    });
    expect(await durability()).toContain("not been requested");
    expect(persist).not.toHaveBeenCalled();
    expect(await durability(true)).toContain("not granted");
    expect(persist).toHaveBeenCalledOnce();
  });
  it("reports grants and unavailable APIs accurately", async () => {
    vi.stubGlobal("navigator", { storage: { persisted: async () => true } });
    expect(await durability()).toContain("granted");
    vi.stubGlobal("navigator", {});
    expect(await durability()).toContain("unavailable");
  });
});
